FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils

ENV RAILS_ROOT /your_application_path

WORKDIR $RAILS_ROOT

RUN mkdir log

COPY public public/

COPY nginx.conf /etc/nginx/

CMD [ "nginx", "-g", "daemon off;" ]
