version: '2'
services:
  db:
    image: postgres

  app: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/new-safety-emergency-web
    ports:
      - "3000:3000"
    depends_on:
      - db

  redis:
    image: redis:3.2-alpine
    command: redis-server
#    ports:
#      - '7479:7479'

  sidekiq:
    build: .
    command: bundle exec sidekiq
    links:
      - db
      - redis

